version: "3.5"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    environment:
      - PORT=8081
    expose:
      - "8081"
    depends_on:
      - postgres
    restart: on-failure
  proxy:
    build:
      context: ./
      dockerfile: ./web/Dockerfile.prod
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - "server.key"
      - "server.crt"
    depends_on:
      - api
    restart: on-failure
  postgres:
    image: postgres:10-alpine
    env_file:
      - .env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    expose:
      - "5432"

secrets:
  "server.key":
    file: ./proxy/server.key
  "server.crt":
    file: ./proxy/server.crt
