version: "3.5"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.${ENV}
    env_file:
      - .env
    volumes:
      - ./api:/go/src/api
    environment:
      - PORT=8081
    expose:
      - "8081"
    depends_on:
      - postgres
    restart: on-failure
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.${ENV}
    env_file:
      - .env
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./web:/home/node/app
    expose:
      - "8080"
    depends_on:
      - api
    restart: on-failure
  postgres:
    image: postgres:alpine@sha256:89c84fcccc147d403916f4d9964bc4d83297ea7c782d79b05dad5b6c172a7dce
    env_file:
      - .env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    expose:
      - "5432"
  proxy:
    image: nginx:alpine@sha256:e5a3c072905c9a30fb29f81b5eb80644f360cfc2b3c47fe0153da614d1dab87a
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - "server.key"
      - "server.crt"
    depends_on:
      - api
      - web
    restart: on-failure

volumes:
  yarn:

secrets:
  "server.key":
    file: ./proxy/server.key
  "server.crt":
    file: ./proxy/server.crt
